--\i Projects/hubbub/blubber/src/blubber_orm/dev/destroy.sql

DROP TABLE addresses CASCADE;
DROP TABLE calendars CASCADE;
DROP TABLE carts CASCADE;
DROP TABLE details CASCADE;
DROP TABLE dropoffs CASCADE;
DROP TABLE extensions CASCADE;
DROP TABLE items CASCADE;
DROP TABLE listers CASCADE;
DROP TABLE logistics CASCADE;
DROP TABLE order_dropoffs CASCADE;
DROP TABLE order_pickups CASCADE;
DROP TABLE orders CASCADE;
DROP TABLE pickups CASCADE;
DROP TABLE profiles CASCADE;
DROP TABLE renters CASCADE;
DROP TABLE reservations CASCADE;
DROP TABLE reviews CASCADE;
DROP TABLE shopping CASCADE;
DROP TABLE tagging CASCADE;
DROP TABLE tags CASCADE;
DROP TABLE testimonials CASCADE;
DROP TABLE users CASCADE;
DROP TABLE issues CASCADE;
